name: CI

on:
 push:
  branches: [main]

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  generate_docker_tag:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.tag.outputs.docker_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get MetaData
        id: metadata 
        run: |
          short_sha=$(echo ${{ github.sha }} | cut -c1-7)
          echo "short sha is : $short_sha" 
          echo "short_sha=$short_sha" >> $GITHUB_ENV
        shell: bash
      
      - name: Set Docker tag
        id: tag
        run: |
          docker_tag="${{ github.ref_name }}_${{ github.run_number }}_${{ env.short_sha }}"
          echo "::set-output name=docker_tag::$docker_tag"

  build:
    needs: generate_docker_tag
    uses: ./.github/workflows/reusable-ci.yaml
    with:
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
      ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
      ROLE_TO_ASSUME: ${{ vars.OIDC_ROLE_TO_ASSUME }}
      DOCKER_TAG: ${{ needs.generate_docker_tag.outputs.docker_tag}}
      FILE_PATH: 'lambda'